version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-template
  php-fpm:
    image: php/php:8.3-fpm
    volumes:
      - ./:/var/www
    build:
      context: ./docker
      args:
        user: $DOCKER_USER_ID
        uid: 1000
    networks:
      - laravel-template
  mysqldb:
      image: mysql
      restart: unless-stopped
      environment:
          MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - ./persistent-data/mysql-data:/var/lib/mysql
      networks:
        - laravel-template

networks:
  laravel-template:
    driver: bridge
